# Generated by Django 5.0.2 on 2024-02-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "front",
                    models.ImageField(blank=True, null=True, upload_to="front-image/"),
                ),
                (
                    "back",
                    models.ImageField(blank=True, null=True, upload_to="back-image/"),
                ),
            ],
        ),
    ]
